### ISSUE TITLE
Expressions checklist

### ISSUE THREAD

**Issue by nukep** [nukep/llamadb#16]
- [x] Numbers
- [x] Strings
- [x] `NULL`
- [ ] Byte arrays
- [x] Subqueries
- [x] Aggregate function calls
- [ ] Scalar function calls
- [x] Binary comparison: `=`, `<>`, `<`, `<=`, `>`, `>=`
- [x] Binary arithmetic: `+`, `-`, `*`, `/`
- [x] Unary `-`
- [x] `AND`
- [x] `OR`
- [ ] `NOT`
- [x] `||`
- [ ] `EXISTS`
- [ ] `BETWEEN` ... `AND`
- [ ] `IN`
- [ ] `CASE`
- [ ] `IS NULL`
- [ ] `IS NOT NULL`
- [ ] `LIKE`
